### ISSUE TITLE
Array syntax in spec

### ISSUE THREAD

**Issue by greenfork** [gruebite/zzz#19]
Is the array syntax

```yaml
array:
  : key: key
    value: value
  : key2: key2
    value2: value2
```

covered in the spec? There's no explicit mention of arrays in the spec and I have troubles understanding if the array syntax naturally flows from some other rules.
